name: actest
channels:
  - conda-forge
dependencies:
  - conda-forge::python=3.9
  - conda-forge::numpy=1.20.1
  - conda-forge::pandas=1.2.2
  - conda-forge::pylint=2.6.0
  - conda-forge::jupyter=1.0.0
  - conda-forge::ipykernel=5.5.0
  - conda-forge::hypothesis=6.3.3
  - pip
  - pip:
      - black==20.8b1
      - pytest==6.2.2
      - pytest-cov==2.11.1
      - pytest-xdist==2.2.1
      - urlpath==1.1.7
      - pytest-datafiles==2.0
