name: actest
channels:
  - conda-forge
dependencies:
  - conda-forge::python=3.7
  - conda-forge::numpy=1.16.4
  - conda-forge::pandas=0.25.1
  - conda-forge::pylint=2.3.1
  - conda-forge::jupyter=1.0.0
  - conda-forge::ipykernel=5.1.1
  - pip
  - pip:
      - black==19.3b0
      - pytest==5.0.1
      - pytest-cov==2.7.1
      - pytest-xdist==1.29.0
      - urlpath==1.1.4
      - pytest-datafiles==2.0
