name: Continuous-Integration
on:
  push:
    branches:
      # Push events on main branch
      - main
      # Push events to branches matching refs/heads/feature/...
      - "feature/**"
  pull_request:
    branches:
      # PR events on main branch
      - main
jobs:
  build:
    name: CI-Process
    runs-on: ubuntu-latest
    # name: Ex1 (${{ matrix.python-version }}, ${{ matrix.os }})
    # runs-on: ${{ matrix.os }}
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    # python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.0.1
        with:
          activate-environment: actest
          environment-file: environment.yml
      - name: Black Code Formatter
        shell: bash -l {0}
        run: |
          make black
      - name: Tests
        shell: bash -l {0}
        run: |
          make test
      - name: Generate coverage report
        shell: bash -l {0}
        run: |
          make coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
