name: CI Process
on:
  push:
    branches:
      # Push events on main branch
      - main
      # Push events to branches matching refs/heads/feature/...
      - "feature/**"
  pull_request:
    branches:
      # PR events on main branch
      - main
jobs:
  build:
    name: CI Process
    runs-on: ubuntu-latest
    # name: Ex1 (${{ matrix.python-version }}, ${{ matrix.os }})
    # runs-on: ${{ matrix.os }}
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    # python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v2
      # - name: Set up Python 3.9
      #   uses: actions/setup-python@v1
      #   with:
      #     python-version: 3.9
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.0.1
        with:
          activate-environment: actest
          environment-file: environment.yml
      - name: Black Code Formatter
        # uses: lgeiger/black-action@v1.0.1
        # with:
        #   args: "--target-version py39 ."
        shell: bash -l {0}
        run: |
          make black
      - name: Tests
        shell: bash -l {0}
        run: |
          make test
      # - name: Test with pytest
      #   run: |
      #     pip install pytest
      #     pytest
      - name: Generate coverage report
        run: |
          pip install pytest
          pip install pytest-cov
          pytest --cov=./ --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          yml: ./codecov.yml
          fail_ci_if_error: true
